// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-6e8hRt_MdbJnsmvfMkI8IXlUXsyjdC0',
    appId: '1:524411589574:web:18f81c99f03e60aed6d8c7',
    messagingSenderId: '524411589574',
    projectId: 'video-downloader-admin',
    authDomain: 'video-downloader-admin.firebaseapp.com',
    storageBucket: 'video-downloader-admin.firebasestorage.app',
    measurementId: 'G-WQ1TT4GV9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ZOi1vygNaYLe3NpcjQ2iAqU7yTqr904',
    appId: '1:524411589574:android:ee1fa5e45ef8c51fd6d8c7',
    messagingSenderId: '524411589574',
    projectId: 'video-downloader-admin',
    storageBucket: 'video-downloader-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEBeh2p40xklrcGgS4nrQ6UsQZ894HcO8',
    appId: '1:524411589574:ios:fa65a15495ed0673d6d8c7',
    messagingSenderId: '524411589574',
    projectId: 'video-downloader-admin',
    storageBucket: 'video-downloader-admin.firebasestorage.app',
    iosBundleId: 'com.example.videoDownloader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEBeh2p40xklrcGgS4nrQ6UsQZ894HcO8',
    appId: '1:524411589574:ios:fa65a15495ed0673d6d8c7',
    messagingSenderId: '524411589574',
    projectId: 'video-downloader-admin',
    storageBucket: 'video-downloader-admin.firebasestorage.app',
    iosBundleId: 'com.example.videoDownloader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-6e8hRt_MdbJnsmvfMkI8IXlUXsyjdC0',
    appId: '1:524411589574:web:08bd5596b4d41773d6d8c7',
    messagingSenderId: '524411589574',
    projectId: 'video-downloader-admin',
    authDomain: 'video-downloader-admin.firebaseapp.com',
    storageBucket: 'video-downloader-admin.firebasestorage.app',
    measurementId: 'G-J76S5681X6',
  );
}
