// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-6e8hRt_MdbJnsmvfMkI8IXlUXsyjdC0',
    appId: '1:524411589574:web:b6a910fdd5fde3c3d6d8c7',
    messagingSenderId: '524411589574',
    projectId: 'video-downloader-admin',
    authDomain: 'video-downloader-admin.firebaseapp.com',
    databaseURL: 'https://video-downloader-admin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-downloader-admin.firebasestorage.app',
    measurementId: 'G-YMBQEBXDMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ZOi1vygNaYLe3NpcjQ2iAqU7yTqr904',
    appId: '1:524411589574:android:3ce879a1fecc3097d6d8c7',
    messagingSenderId: '524411589574',
    projectId: 'video-downloader-admin',
    databaseURL: 'https://video-downloader-admin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-downloader-admin.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-6e8hRt_MdbJnsmvfMkI8IXlUXsyjdC0',
    appId: '1:524411589574:web:42bfb96665f3c1acd6d8c7',
    messagingSenderId: '524411589574',
    projectId: 'video-downloader-admin',
    authDomain: 'video-downloader-admin.firebaseapp.com',
    databaseURL: 'https://video-downloader-admin-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'video-downloader-admin.firebasestorage.app',
    measurementId: 'G-04GVWM8FRJ',
  );
}
